imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    blogger_blog.emails.contact_email: nghiepnt94@gmail.com

framework:
    #esi:             ~
    translator:      { fallbacks: [en] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "en"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        cdn: "/"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"



vich_uploader:
    db_driver: orm

    mappings:
        post_image:
            uri_prefix:         upload/post/
            upload_destination: %kernel.root_dir%/../web/upload/post
            namer:              mosaicfilenamer
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false
        news_image:
            uri_prefix:         upload/news/
            upload_destination: %kernel.root_dir%/../web/upload/news
            namer:              mosaicfilenamer
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false
        project_image:
            uri_prefix:         upload/project/
            upload_destination: %kernel.root_dir%/../web/upload/project
            namer:              mosaicfilenamer
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false
        project_group_image:
            uri_prefix:         upload/projectgroup/
            upload_destination: %kernel.root_dir%/../web/upload/projectgroup
            namer:              mosaicfilenamer
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false
        category_image:
            uri_prefix:         upload/category/
            upload_destination: %kernel.root_dir%/../web/upload/category
            namer:              mosaicfilenamer
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false
        glaze_image:
            uri_prefix:         upload/glaze/
            upload_destination: %kernel.root_dir%/../web/upload/glaze
            namer:              mosaicfilenamer
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false
        pattern_image:
            uri_prefix:         upload/pattern/
            upload_destination: %kernel.root_dir%/../web/upload/pattern
            namer:              mosaicfilenamer
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false
        color_image:
            uri_prefix:         upload/color/
            upload_destination: %kernel.root_dir%/../web/upload/color
            namer:              mosaicfilenamer
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false
        product_image:
            uri_prefix:         upload/product/
            upload_destination: %kernel.root_dir%/../web/upload/product
            namer:              mosaicfilenamer
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false

ivory_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []

fm_elfinder:
    instances:
        default:
            relative_path: false
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to true
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: images
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 20M